---
language: node_js
node_js:
  - "6"

sudo: required

env:
  - MOZ_HEADLESS=1

addons:
  chrome: stable
  firefox: latest

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version

install:
  - yarn install --non-interactive --pure-lockfile
  - bower install

script:
  - npm test
